using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using hw.DebugFormatter;
using hw.Helper;
using ManageModsAndSavefiles;
using ManageModsAndSavefiles.Saves;
using MmasfUI.Common;

namespace MmasfUI
{
    sealed class UserConfigurationWindow : Window
    {
        readonly UserConfiguration Configuration;
        bool IsSaves;
        readonly FileClusterProxy[] Data;
        TextBlock StatusTextControl;

        public UserConfigurationWindow(ViewConfiguration viewConfiguration)
        {
            var configuration = MmasfContext
                .Instance
                .UserConfigurations.Single(u => u.Name == viewConfiguration.Name);

            IsSaves = viewConfiguration.Type == ViewConfiguration.SavesType;
            StatusTextControl = new TextBlock();
            Configuration = configuration;

            Data = Configuration
                .SaveFiles
                .Select(s => new FileClusterProxy(s))
                .ToArray();

            Content = CreateGrid();

            Title = viewConfiguration.Type + " of " + configuration.Name.Quote();
            this.InstallPositionPersister(viewConfiguration.PositionPath);
            this.InstallMainMenu(CreateMenu());
            this.InstallStatusLine(CreateStatusLine());
        }

        ScrollViewer CreateGrid()
        {
            var result = new DataGrid
            {
                ItemsSource = Data,
                IsReadOnly = true
            };
            result.AutoGeneratingColumn += (s, e) => OnAutoGeneratingColumns((DataGrid) s, e);
            result.AutoGeneratedColumns += (s, e) => OnAutoGeneratedColumns((DataGrid) s);

            Task.Factory.StartNew
            (
                () =>
                {
                    Thread.CurrentThread.Priority = ThreadPriority.AboveNormal;
                    "waiting".WriteFlaggedLine();
                    100.MilliSeconds().Sleep();

                    Tracer.FlaggedLine("Refreshing");
                    RefreshData();
                    Tracer.FlaggedLine("Refreshed");
                }
            );

            return new ScrollViewer
            {
                Content = result,
                VerticalScrollBarVisibility = ScrollBarVisibility.Auto,
                HorizontalScrollBarVisibility = ScrollBarVisibility.Auto
            };
        }

        static void OnAutoGeneratingColumns
        (
            DataGrid grid,
            DataGridAutoGeneratingColumnEventArgs args)
        {
            if(args.PropertyType != typeof(MyTimeSpan))
                return;

            var column = (DataGridTextColumn) args.Column;
            column.SortMemberPath += ".Value";
            ((Binding) column.Binding).Path.Path += ".DisplayValue";
            column.CanUserSort = true;
        }


        static void OnAutoGeneratedColumns(DataGrid grid) { }

        void RefreshData()
        {
            Tracer.FlaggedLine("loop");
            var count = Data.Length;
            var current = 0;
            Parallel.ForEach
            (
                Data, proxy =>
                {
                    proxy.Refresh();
                    current++;
                    RefreshStatus(current + " of " + count);
                });

            RefreshStatus(count.ToString());
        }



        void RefreshStatus(string text)
        {
            this.InvokeIfRequired(()=>StatusTextControl.Text = text);
        }

        public sealed class MyTimeSpan : DumpableObject, INotifyPropertyChanged
        {
            public TimeSpan Value { get; set; }

            public MyTimeSpan(TimeSpan value)
            {
                Value = value;
                OnPropertyChanged();
            }

            public string DisplayValue => Value.Format3Digits();
            public override string ToString() => Value.Format3Digits();

            public event PropertyChangedEventHandler PropertyChanged;

            void OnPropertyChanged()
                => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
        }

        sealed class FileClusterProxy : INotifyPropertyChanged
        {
            readonly FileCluster FileCluster;

            public string Name => FileCluster.Name;

            public Version Version { get; set; }
            public MyTimeSpan Duration { get; set; }

            public FileClusterProxy(FileCluster fileCluster) { FileCluster = fileCluster; }

            public void Refresh()
            {
                Version = FileCluster.Version;
                Duration = new MyTimeSpan(FileCluster.Duration);
                OnPropertyChanged();
            }

            public event PropertyChangedEventHandler PropertyChanged;

            void OnPropertyChanged()
                => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
        }

        UIElement CreateStatusLine()
        {
            var result = new StatusBar();
            StatusTextControl = new TextBlock();
            result.Items.Add(StatusTextControl);
            return result;
        }


        static Menu CreateMenu()
            => new Menu
            {
                Items =
                {
                    new MenuItem
                    {
                        Header = "_File",
                        Items =
                        {
                            "_Exit".MenuItem("Exit")
                        }
                    }
                }
            };
    }
}